
- action:
  - data:
      brightness: '100'
      entity_id: light.light_1
      kelvin: '2000'
      transition: '600'
    service: light.turn_on
  alias: Wake up
  initial_state: 'on'
  condition: []
  id: '1520550096070'
  trigger:
  - at: 07:30:00
    platform: time
- action:
  - data:
      brightness: '10'
      entity_id: light.light_4
      kelvin: '4000'
      transition: '0'
    service: light.turn_on
  alias: Wake up 2
  initial_state: 'on'
  condition: []
  id: '1520550356855'
  trigger:
  - at: 07:40:00
    platform: time

- action:
  - data:
      brightness: '255'
      entity_id: light.olohuone
      kelvin: '4000'
      transition: '600'
    service: light.turn_on
  alias: Wake up 3
  initial_state: 'on'
  condition: []
  id: '1520550356855'
  trigger:
  - at: 07:41:00
    platform: time

- trigger:
    platform: time
    seconds: '/1'
  alias: Every second flashpy
  initial_state: 'off'
  action:
    - data:
        brightness: '255'
        entity_id: light.light_1
        kelvin: '4000'
        transition: '600'
      service: python_script.flash



- alias: Cube
  trigger:
    - platform: event
      event_type: deconz_event
  action:
    - service: python_script.cube
      data_template:
        id: '{{ trigger.event.data.id }}'
        event: '{{ trigger.event.data.event }}'


- alias: Turn on light when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.presence_4
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.light_2

- alias: Turn off light after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.presence_4
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.light_2
