homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 60.1975
  longitude: 24.875
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  # Customization file
  customize: !include customize.yaml

python_script:

#hello_state:
modify_light:

input_boolean:
  hello_state_on:
    name: Flash
    initial: off
  brightness_is_controlled:
    name: Brightness is controlled
input_number:
  slider1:
    name: Default brightness
    initial: 30
    min: 0
    max: 255
    step: 1

# Enables the frontend
frontend:

# Enables configuration UI
config:

# device_tracker:
#   - platform: bluetooth_le_tracker

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  #ssl_certificate: /etc/letsencrypt/live/examplehome.duckdns.org/fullchain.pem
  #ssl_key: /etc/letsencrypt/live/examplehome.duckdns.org/privkey.pem
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

#deconz:
#   host: 192.168.10.48

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: debug
  logs:
    pydeconz: debug
    homeassistant.components.websocket_api: error
    pychromecast: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

#  - platform: random
#    minimum: 0
#    maximum: 255
#    scan_interval: 1
#  - platform: random
#    scan_interval: 1
#    minimum: 0
#    maximum: 255
#  - platform: random
#    scan_interval: 1
#    minimum: 0
#    maximum: 255
# Text to speech
tts:
  - platform: google

# Cloud
cloud:

light:


scene:
  - name: Bright day
    entities:
      light.light_1:
        state: on
        kelvin: 4000
        brightness: 255
  - name: Normal
    entities:
      light.light_1:
        state: on
        kelvin: 2700
        brightness: 255
  - name: Dim red
    entities:
      light.light_1:
        state: on
        kelvin: 2000
        brightness: 2
  - name: Blue
    entities:
      light.light_1:
        state: on
        kelvin: 6500
  - name: Red
    entities:
      light.light_1:
        state: on
        kelvin: 2000

switch:
  - platform: flux
    lights:
      - light.light_1
    name: Fluxer
    start_time: '08:17'
    stop_time: '23:20'
    start_colortemp: 4000
    sunset_colortemp: 2000
    stop_colortemp: 6000
    brightness: 100
    mode: mired
    transition: 1


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
