version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:0.87.0  #0.76.2
    volumes:
      - /homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
  nodered:
    container_name: nodered
    image: nodered/node-red-docker:rpi-v8
    ports:
      - "1880:1880"
    volumes:
      - /homeassistant/nodered:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/TZ:ro
    environment:
      - TZ='Europe/Helsinki' 
    restart: always
